name: Go

on:
  push:
    branches: [ refactorToHexagonal ]
  pull_request:
    branches: [ refactorToHexagonal ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      working-directory: ./cmd/beers-cli
      run: go build -v  

    - name: Test
      working-directory: ./application/fetching
      run: go test -v  service_test.go
